apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  POSTGRES_DB: UserDb  
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*"
    }