apiVersion: batch/v1
kind: Job
metadata:
  name: "db-migration-job"
spec:
  template:    
    spec:
      activeDeadlineSeconds: 180
      restartPolicy: Never
      initContainers:
        - name: check-db-ready
          image: postgres:latest
          env:
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
          command:
            - sh
            - "-c"
            - |
              until pg_isready -h $POSTGRES_HOST  -p  $POSTGRES_PORT; 
              do echo waiting for database; sleep 2; done;
      containers:
        - name: db-migration-job
          image: stilux/user-api:v1
          args: ["-m"]
          volumeMounts:
            - name: config-volume
              mountPath: "/app/config"
              readOnly: true
      volumes:
        - name: config-volume
          secret:
            secretName: app-secret
            items:
              - key: appsettings.secrets.json
                path: appsettings.json
  backoffLimit: 0