apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  POSTGRES_USER: YXBpLXVzZXI=
  POSTGRES_PASSWORD: Qno4fnVyalc=
  appsettings.secrets.json: ewogICJDb25uZWN0aW9uU3RyaW5ncyI6IHsKICAgICJVc2VyRGJDb25uZWN0aW9uIjogIlVzZXJJRD1hcGktdXNlcjtQYXNzd29yZD1Cejh+dXJqVztTZXJ2ZXI9cG9zdGdyZXM7UG9ydD01NDMyO0RhdGFiYXNlPVVzZXJEYjtJbnRlZ3JhdGVkIFNlY3VyaXR5PXRydWU7UG9vbGluZz10cnVlOyIKICB9Cn0=