---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-import-dashboards
  labels:
    grafana-dashboard: {{ include "user-api.name" . }}
data:
  user-api-dashboard.json: |
    {{- .Files.Get "grafana/user-api-dashboard.json" | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-api.fullname" . }}
  labels:
    {{- include "user-api.selectorLabels" . | nindent 4 }}
data:   
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": {{ .Values.api.logLevel | quote }},
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": {{ .Values.api.allowedHosts | quote }}
    }