apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-api.fullname" . }}
  labels:
    {{- include "user-api.selectorLabels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.dataBase.user | b64enc }}
  DB_PASSWORD: {{ .Values.dataBase.password | b64enc }}
  appsettings.secrets.json: {{ tpl (.Files.Get "config/appsettings.secrets.json") . | b64enc }}