{{- if .Values.ingress.enabled -}}
{{- $fullName := include "user-api.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}  
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:  
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.main.paths }}
          - path: {{ . }}($|/)(.*)
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}    
    {{- end }} 

---
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-swagger
spec:
  rules:    
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:          
          - path: {{ .Values.ingress.swagger.path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
{{- end }}
