---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-api.fullname" . }}
  labels:
    {{- include "user-api.selectorLabels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "user-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:    
      labels:
        {{- include "user-api.selectorLabels" . | nindent 8 }}        
      annotations:
        {{- include "user-api.configChangeDetection" . | nindent 8 }}
    spec:      
      containers:
        - name: {{ .Chart.Name }}          
          image: {{ include "user-api.fullImageName" . }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.api.configPath | quote }}
              readOnly: true                   
      volumes:
        - name: config-volume
          projected:
            sources:
              - configMap:
                  name: {{ include "user-api.fullname" . }}
                  items:
                    - key: appsettings.json
                      path: appsettings.json
              - secret:
                  name: {{ include "user-api.fullname" . }}
                  items:
                    - key: appsettings.secrets.json
                      path: appsettings.secrets.json

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "user-api.fullname" . }}
  labels:
    {{- include "user-api.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "user-api.fullname" . }}
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "user-api.selectorLabels" . | nindent 6 }}
  endpoints:
    - interval: 15s
      port: web
      path: /metrics