---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-api.fullname" . }}
  labels:
    {{- include "user-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "user-api.selectorLabels" . | nindent 4 }}  

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-api.postgresFullname" . }}
  labels:
    {{- include "user-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.dataBase.port }}
  selector:
    {{- include "user-api.postgresSelectorLabels" . | nindent 4 }}