apiVersion: v2
name: user-api
description: A Helm chart for Kubernetes

type: application

version: 1.0.0
appVersion: 1

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - user-api-database