postgresql:
  enabled: true
  postgresqlUsername: "api-user"
  postgresqlPassword: "Bz8~urjW"
  postgresqlDatabase: "UserDb"
  service:
    port: "5432"
  image:
    tag: "latest"
  persistence:
    size: 1Gi 
  metrics:
    enabled: true    
    serviceMonitor:
      enabled: true      
      namespace: monitoring
      interval: 30s
      scrapeTimeout: 10s
      
api:
  image:
    repository: "stilux/user-api"
    pullPolicy: IfNotPresent
  replicaCount: 2
  configPath: "/app/config"
  logLevel: "Information"
  allowedHosts: "*"
  
service:
  type: "NodePort"
  port: 80

ingress:
  enabled: true
  host: "arch.homework"
  main:   
    paths: 
      - "/otusapp"
  swagger:
    path: "/swagger"
    
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80