{
 "title": "User-API",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"monitoring\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"monitoring\", container!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency (max)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency (max)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, \r\n      sum by (le, action) \r\n         (rate(http_request_duration_seconds_bucket{controller=\"User\"}[2m]))\r\n) * 1000\r",
       "legendFormat": "{{action}}, ms"
      }
     ]
    },
    {
     "title": "Latency Ingress (max)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])) by (le)) * 1000",
       "legendFormat": "Latency, ms"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency (0.99)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency (0.99)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \r\n      sum by (le, method) \r\n         (rate(http_request_duration_seconds_bucket{controller=\"User\"}[2m]))\r\n) * 1000\r",
       "legendFormat": "{{method}}, ms"
      }
     ]
    },
    {
     "title": "Latency Ingress (0.99)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])) by (le)) * 1000",
       "legendFormat": "Latency, ms"
      }
     ]
    }
   ]
  },
  { "title": "Latency (0.95)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Latency (0.95)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \r\n      sum by (le, action) \r\n         (rate(http_request_duration_seconds_bucket{controller=\"User\"}[2m]))\r\n) * 1000\r",
     "legendFormat": "{{action}}, ms"
    }
   ]
  },
  {
   "title": "Latency  Ingress (0.95)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])) by (le)) * 1000",
     "legendFormat": "Latency, ms"
    }
   ]
  },
  {
   "title": "Latency (0.5)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency (0.5)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, \r\n      sum by (le, action) \r\n         (rate(http_request_duration_seconds_bucket{controller=\"User\"}[2m]))\r\n) * 1000\r\n",
       "legendFormat": "{{action}}, ms"
      }
     ]
    },
    {
     "title": "Latency Ingress (0.5)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])) by (le)) * 1000",
       "legendFormat": "Latency, ms"
      }
     ]
    }
   ]
  },
  { "title": "RPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (action) (rate(http_requests_received_total{controller=\"User\"}[2m]))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "RPS Ingress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(nginx_ingress_controller_request_duration_seconds_count[2m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (action, code) (increase(http_requests_received_total{code=~\"5.+\", controller=\"User\"}[2m]))",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Error Rate Ingress",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[2m]))",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Database Deadlocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_database_deadlocks[2m]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Database Locks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (rate(pg_locks_count{datname=\"UserDb\"}[2m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  }
 ]
}